name: Build and Deploy

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            GIT_COMMIT: ${{ github.sha }}

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: "18.17"
                  cache: "npm"
                  cache-dependency-path: |
                      package-lock.json

            - name: npm ci
              run: |
                  npm ci

            - name: npm test
              run: |
                  npm run test

            - name: npm build
              run: |
                  npm run build

            - uses: actions/upload-artifact@v3
              with:
                  name: client
                  path: |
                      dist
                  if-no-files-found: error
                  retention-days: 3

    deploy:
        runs-on: ubuntu-latest

        needs: build

        steps:
            - uses: actions/checkout@v3

            - uses: actions/download-artifact@v3
              with:
                  name: client
                  path: out

            - name: deploy to gh-pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  single-commit: true
                  repository-name: aolagers/pointz-www
                  token: ${{ secrets.DEPLOY_PAGE_TOKEN }}
                  folder: out
                  target-folder: .
